[package]
name = "dashboard"
version = "0.1.0"
description = "Projects dashboard"
authors = ["Dmytro Banin <dima_banin@hotmail.com>"]
license = "MIT"
edition = "2024"

[dependencies]
cargo_metadata = "0.23"
crossterm = { version = "0.28.1", features = ["event-stream"] }
ratatui = "0.30.0"
tokio = { version = "1.40.0", features = ["full"] }
color-eyre = "0.6.3"
futures = "0.3"
nucleo = "0.5"
ratatui-cheese = "0.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tui-input = "0.15"
sysinfo = "0.37"
unicode-width = "0.2"
toml = "0.9"
portable-pty = "0.9"
vt100 = "0.16"
tui-term = "0.3.4"

# Read the optimization guideline for more details: https://ratatui.rs/recipes/apps/release-your-app/#optimizations
[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
